#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the solve function below.
def solve(s):
    x=s.split(" ")
    a=0
    f=""
    for i in x:
        a=a+1
    for i in range(a):
        for j,k in enumerate(x[i]):
            if k.isalpha():
                if j==0:
                    f=f+k.upper()
                else:
                    f=f+k
            else:
                f=f+k
        f=f+" "
    return f
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = solve(s)

    fptr.write(result + '\n')

    fptr.close()
